port: 8080

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 1800

mongo:
  uri: "mongodb+srv://isr_adm:Lucca19042021@isr-consulting.hiy9a.gcp.mongodb.net/?retryWrites=true&w=majority"
  name: "testdb"
  login_collection: "logins"
  users_collection: "users"